peburrows/goth

mix.exs

A build with mix release will crash without this dependency.
```elixir
%UndefinedFunctionError{arity: 1, function: :private_key, module: JsonWebToken.Algorithm.RsaUtil, reason: nil}`
```

Adding dependency to ensure build with exrm works

---

lib/goth/token_store.ex
test/goth/token_store_test.exs

Sometimes (at least happens on dev machines which go to _sleep_), the tokens are not being automatically refreshed (probably because the erlang time lags behind the os time, and also because `:timer.apply_after` only guarantees "not sooner than", but can be much later), which causes authentication issues.
This commit checks the `expires` value against the OS time and, if the token (although present on the `TokenStore`) has expired, it is removed and an `:error` is returned (same as if it were missing). This will cause a new token to be requested.

Treat expired tokens as missing

---

README.md
lib/goth/token.ex

As per https://developers.google.com/identity/protocols/OAuth2ServiceAccount#callinganapi

Instruct users to use space delimited scopes

---

README.md
lib/goth/client.ex
lib/goth/config.ex
mix.exs
test/goth/client_test.exs
test/goth/config_test.exs
test/goth/token_store_test.exs
test/goth/token_test.exs

Applications running on Google Cloud Platform can transparently request tokens from the metadata service, if the instance they are running on has appropriate permissions.
This change makes Goth compatible with token retrieval through the metadata service. Existing configuration does not need to be changed, as the presence of the `:json` key will automatically cause retrieval to use the standard OAuth token provider instead.
Scopes are not currently checked for tokens from the metadata service, however this should be trivial to add by comparing with the output of the `/scopes` endpoint. I just haven't had the time yet!
Other notes:
* Some minor cleanups for readability - highly subjective!
* I removed the Config process. The setter functionality didn't seem to be in use and it provided no …

Support for Google Cloud Platform metadata

---

lib/goth/client.ex
test/goth/client_test.exs

When an api fails, let's say the client is deleted, or other various reasons, the current implementation is pretty vague on the reason why the token fetch fails, it would display something like `** (ArithmeticError) bad argument in arithmetic expression`.
My implementation is not perfect since it does treat each error use cases but it's a bit more explanatory.

Return errors when API calls fail

---

.gitignore
config/test.exs
lib/goth/client.ex
lib/goth/config.ex
test/data/home/gcloud/application_default_credentials.json
test/data/test-credentials-2.json
test/data/test-credentials.json
test/goth/client_test.exs
test/goth/config_test.exs

The overall goal here is to complete support for [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials). This PR provides an implementation of the last piece, gcloud sdk credentials provided by `gcloud auth application-default login`.
It involves two general parts:
1. The logic for resolving the configuration in `config.ex` now includes a step looking for a credentials file in the well-known path used by gcloud. This location is `$HOME/.config/gcloud/application_default_credentials.json` on unix systems, but `%APPDATA%\gcloud\application_default_credentials.json` on windows. (I picked up this logic from the [Ruby auth library](https://github.com/google/google-auth-library-ruby.)
2. Gcloud-provided ADCs are in the form of a …

Honor credentials from gcloud application defaults

---

lib/goth/config.ex

I was a bit puzzled by this error:
`* (Mix) Could not start application goth: Goth.start(:normal, []) returned an error: shutdown: failed to start child: Goth.Config
** (EXIT) an exception was raised:
** (HTTPoison.Error) :nxdomain
...
`
So I added a try-rescue block to catch this `:nxdomain` error and show how to fix it when it occurs.

Add informative error message when the project ID can't be automatically found

---

lib/goth/client.ex
lib/goth/token.ex
lib/goth/token_store.ex
test/goth/client_test.exs
test/goth/token_store_test.exs
test/goth/token_test.exs

This PR preserves all the existing APIs while adding `sub` support.
In `Token` and `TokenStore`, `sub` is added as an additional parameter in most functions. 
In `Client`, since we need to accommodate `iat`, I introduced `opts`, which can be used for either, or both `iat` and `sub`. The API signature `jwt(scope, iat)` is preserved, however I recommend deprecate them in favor of `jwt(scope, iat: iat)`. This also leaves room for potential other optional fields in the future.
Also wrote tests and docs for it.
Fix #29.

Add support for sub

---

lib/goth/config.ex
lib/goth/token.ex
lib/goth/token_store.ex

The new sub parameter for a few of the `Token` functions has a default value of `nil`, but this wasn't reflected in the type spec. This meant that dialyzer simply concluded that the function could never finish and so anything that used these functions simply propagated that.
I noticed this because entire trees of execution in one of our projects were marked as having no local return, so this error bubbles up to the top, making dialyzer effectively useless for whatever uses `Goth .
This also addresses #31

Fix dialyzer errors stemming from mis-specced functions with new `sub` parameter

---

lib/goth/token_store.ex

Fix for this warning message - 
```ex
warning: function init/1 required by behaviour GenServer is not implemented (in module Goth.TokenStore).
We will inject a default implementation for now:
def init(args) do
{:ok, args}
end
But you want to define your own implementation that converts the arguments given to GenServer.start_link/3 to the server state
```

TokenStore - Define init/1 required by behaviour GenServer

---

lib/goth/config.ex
test/goth/config_test.exs

While using this module for an application, a use-case came up to dynamically add service users (defined at runtime by using admin APIs). I do not believe any of the existing config definition methods allow this, so I went ahead and added a function to allow this in the Config module.
Let me know if there is a preferable implementation here, or an existing way to get the same functionality.

dynamically add account configs

---

lib/goth/token.ex

When calling `Token.for_scope({String.t(), String.t()})`, a Dialyzer warning is seen. The `for_scope` `spec` has been changed to cover this case and now aligns with the `TokenStore.find` `spec`, since `for_scope` calls `find` with the same arguments.

change for_scope spec to accept {String.t(),String.t()}

---

README.md
lib/goth/config.ex
test/goth/config_test.exs

E.g. when your dev mode doesn't require access to GCS and you therefore don't
have a valid service account configuration avaliable.

Allow for disabling Goth in your config

---

.travis.yml

💁 Adds the following versions to the CI build matrix:
* Erlang/OTP: 22.0
* Elixir: 1.9, 1.10
I've added exclusions to this build matrix based on the Elixir <> Erlang/OTP compatibility information provided in https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp.

CI: Add new Elixir and Erlang/OTP versions

---

mix.exs

This will enable newer versions of Elixir to run the tests and pass. While warnings should probably be resolved, many of them exist in underlying dependencies, and should therefore not fail the suite.

Remove the `warnings_as_errors` compiler option

---

lib/goth/config.ex

This is to support use cases where a developer has used `gcloud auth
application-default login` and `gcloud auth application-default
set-quota-project $PROJECT_ID` and expects applications to use those
configuration values as a result.

Add another fallback to use the quota project from a credentials file

---

README.md
lib/goth.ex
lib/goth/token.ex
test/goth/token_test.exs
test/goth_test.exs

Hi @peburrows and @wojtekmach - I'm loving the redesign for v1.3!
This PR attempts to get the ball rolling for instance metadata support. WDYT?
Ref: #82

Support fetching tokens from compute instance metadata

---

lib/goth.ex
lib/goth/server.ex
lib/legacy/application.ex
lib/legacy/supervisor.ex

Hi @peburrows 
I'd tried to complete https://github.com/peburrows/goth/issues/82#issuecomment-849894699
Just one thing that is not properly handled is how we start the Registry process as part of the supervision tree of the library, as `Goth.Application` module is already defined on the legacy folder, I wasn't able to provide a better solution sorry about it.

Use Registry to register Goth servers

---

lib/goth/token.ex
test/goth/token_test.exs

I've found a workaround for the `target_audience` claim required by Google Cloud Functions: the same effect can be achieved with the `scope` JWT claim.
With that in mind, the only change required was to handle the OAuth ID response.

Goth.Token recognize OAuth ID token responses

---

README.md

Hi.
I recently needed to work in a project using more than one credentials at the same time and I have to figure out how to configure `goth` to work with more than one credentials.
Once it's working I'd like to add an example to the README.md about how to do it.
Thanks.

Add example for multiple credentials

---

.formatter.exs
lib/goth/token.ex
lib/legacy/config.ex
test/goth/token_test.exs
test/goth_test.exs
test/legacy/token_test.exs

This PR allows overriding self-signed JWT claims. Which in turn makes it easier to follow different token exchange scenarios:
```
iex> credentials = "credentials.json" |> File.read!() |> Jason.decode!()
...> claims = %{"target_audience" => "https://<GCP_REGION>-<PROJECT_ID>.cloudfunctions.net/<CLOUD_FUNCTION_NAME>"}
...> Goth.Token.fetch(%{source: {:service_account, credentials, [claims: claims]}})
{:ok, %Goth.Token{...}}
```
```
iex> credentials = "credentials.json" |> File.read!() |> Jason.decode!()
...> claims = %{"sub" => "<IMPERSONATED_ACCOUNT_EMAIL>"}
...> Goth.Token.fetch(%{source: {:service_account, credentials, [claims: claims]}})
{:ok, %Goth.Token{...}}
```

Self-signed JWT claim overrides

---

lib/goth/token.ex
test/goth_test.exs

I've found this when trying to use the `http_client: &Req.request/1` option, because the body was already decoded by [`Req`](https://github.com/wojtekmach/req)
```elixir
* 1st argument: not an iodata term
:erlang.iolist_to_binary(%{"access_token" => "...", "expires_in" => 3599, "token_type" => "Bearer"})
(jason 1.3.0) lib/jason.ex:69: Jason.decode/2
(goth 1.3.0-rc.4) lib/goth/token.ex:277: Goth.Token.handle_response/1
(goth 1.3.0-rc.4) lib/goth/token.ex:213: Goth.Token.request/1
(goth 1.3.0-rc.4) lib/goth.ex:213: Goth.prefetch/1
(goth 1.3.0-rc.4) lib/goth.ex:206: Goth.handle_continue/2
(stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
Last message: {:continue, :async_prefetch}
```
With this PR, it solves the bug and we can …

Add pattern matching when body is already a map

---

lib/goth.ex
test/goth_test.exs

As discussed on #134, we're reverting the `:refresh_after` implementation to the old `:refresh_before`.

Revert from `:refresh_after` to `:refresh_before`

---

lib/goth.ex
test/goth_test.exs

Whenever host machine goes to sleep there is a chance Goth will not refresh token. For cases like this we want to force refresh if the token retrieved from the ets is expired.
See https://github.com/peburrows/goth/issues/134#issuecomment-1190539099

Force refresh whenever token retrieved from ets is expired

---

lib/goth/token.ex

A tiny fix for shorthand metadata source configuration:
`{Goth, name: MyApp.Goth}` - broken
`{Goth, name: MyApp.Goth, source: :metadata}` - broken
`{Goth, name: MyApp.Goth, source: {:metadata, []}}` - works
Got this issue while migrating my app from using credentials file to Workload Identity.
Stacktrace:
```
(CaseClauseError) no case clause matching: %Goth{http_client: {#Function<3.71762554/1 in Goth."-fun.__finch__/1-">, []}, max_retries: 10, name: MyApp.Goth, refresh_before: 300, retries: 0, retry_after: nil, retry_delay: #Function<4.71762554/1 in Goth."-fun.exp_backoff/1-">, source: {:metadata, []}}
(goth 1.3.0) lib/goth.ex:194: Goth.prefetch/1
(goth 1.3.0) lib/goth.ex:187: Goth.handle_continue/2
(stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.17.2) …
```

Fixed getting tokens from metadata with no options provided

---

lib/goth/token.ex

Changed `System.system_time(:second)` to `System.os_time(:second)` per the recommendation in #147.
Note that the skew, at least on my system, was pretty extreme:
```elixir
{:system_time, {:ok, ~U[2023-04-28 11:22:57Z]}}
{:os_time, ~U[2023-04-28 18:38:17.936225Z]}
```

change to os_time to prevent unmanagable clock skew

---

lib/goth.ex
mix.exs

Use Logger.warning/2, as Logger.warn/2 is deprecated.
Reference: https://hexdocs.pm/logger/main/Logger.html#warn/2

Use Logger.warning/2

---

lib/goth.ex
lib/goth/token.ex

currently `System.system_time` is used to get current time, which is used for checking whether the token is expired. `System.system_time` is affected by time warp
note that the lag between `:os.system_time` and `System.system_time` was a lot in my case
```elixir
iex(..)11> :os.system_time(:second) - System.system_time(:second)
96776
```
due to this, `Goth.fetch` returns expired tokens which are no longer valid. the only solution when this happens is to reboot the system. This PR changes it to use `:os.system_time`.

change to :os.system_time to avoid using invalid time while checking token expiry

---

lib/goth/token.ex
test/data/test-credentials-direct-workload-identity-json.json
test/data/test-credentials-direct-workload-identity.json
test/data/workload-identity-token.json
test/goth/token_test.exs

1. Direct workload identity federation does not require service account impersonation in order to exchange an access token. Commit 7219e27 adds support for direct access token exchange.
2. When given [file-sourced credentials][0], they may be in either text (default) or json format. When the json format is used, a subject_token_name_field must be present. Commit 2a30438 adds support for json credential sources as well as missing (default) format.
[0]: https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers#file-sourced-credentials

Support direct workload identity federation and more credential_source options

---

lib/goth/token.ex
test/data/test-credentials-url-workload-identity.json
test/goth/token_test.exs

Add the ability to fetch the `subject_token` for a workload identity from a url. Also added some documentation in `token.ex` for using `:workload_identity`. This allows us to use workload identity directly without any additional steps in our CI actions based on how we have configured workload identity.
I was able to get it working with the previous commits to `master` here, by making an additional `curl`, but with this we can just use the credentials json directly

Support fetching subject token from url for workload identity

---

lib/goth/token.ex

Currently, workload identity only supports Google Cloud Platform scope.
This change enables Goth to fetch the token for the specified scopes using workload identity with the following config:
```
source: {:workload_identity, credentials, scopes: scopes}
```

Support the scopes option in workload identity
